### ISSUE TITLE
add github actions as a ci option

### ISSUE THREAD

**Issue by travi** [form8ion/utils-cli#793]
add https://github.com/form8ion/github-actions-node-ci to https://github.com/form8ion/utils-cli/blob/d60dad4dd3fe53d4fe19b103a17c29339b8d502e/src/commands/scaffold/enhanced-scaffolders.js#L15 with key `GitHub Actions`

**Comment by travi** [comment]
sorry, @trevtrich, i'm stealing this one so i can leverage it to create a gatsby scaffolder

**Comment by trevtrich** [comment]
sweet, didn't know you had already knocked the github actions ci out 👍

**Comment by travi** [comment]
its still not as full featured as the travis one, but getting there
